language: python

python:
  - '2.7'

env:
  matrix:
    # Django 1.5
    - COMBO="Django==1.5.8 django-oscar==0.6.5"
    - COMBO="Django==1.5.8 django-oscar==0.7.2"
    # Django 1.6
    - COMBO="Django==1.6.5 django-oscar==0.6.5"
    - COMBO="Django==1.6.5 django-oscar==0.7.2"
    - COMBO="Django==1.6.5 South==1.0 https://github.com/tangentlabs/django-oscar/archive/master.tar.gz#egg=django-oscar"
    # Django 1.7
    - COMBO="Django==1.7 django-oscar==1.0"

matrix:
  include:
    - python: '3.3'
      env: COMBO="Django==1.7 django-oscar==1.0"
    - python: '3.4'
      env: COMBO="Django==1.7 django-oscar==1.0"

install:
  - pip install $COMBO -r requirements.txt
  - python setup.py develop

script:
  - coverage run ./runtests.py

after_success:
  - coveralls
